### ISSUE TITLE
Deleting a habit breaks update/delete for orphaned resources

### ISSUE THREAD

**Issue by JamesKoenig** [JamesKoenig/FieldLily#32]
steps to reproduce
1. create a habit
2. create a resource for that habit
3. delete habit

the created resource now causes the following backend error when update/delete are attempted on it:
```
(node:12419) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of null
[0]     at Habit.findById.then (/home/comstar/development/AppAcademy/FieldLily/routes/api/resources.js:87:31)
[0]     at process._tickCallback (internal/process/next_tick.js:68:7)
[0] (node:12419) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:12419) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] (node:12419) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of null
[0]     at Habit.findById.then (/home/comstar/development/AppAcademy/FieldLily/routes/api/resources.js:87:31)
[0]     at process._tickCallback (internal/process/next_tick.js:68:7
```
the promise hangs for a while waiting for a reply before eventually receiving a `500` error

**Comment by JamesKoenig** [comment]
fixed by #34
